services:
  app:
    image: ghcr.io/zahid-afridi/izo-crm:latest
    container_name: izo-crm-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - izo-net

networks:
  izo-net:
    driver: bridge
